import socket
import select
import sys
import os
import textwrap

server_address = ('127.0.0.1', 80)
server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
server_socket.bind(server_address)
server_socket.listen(5)

input_socket = [server_socket]

try:
    while True:
        read_ready, write_ready, exception = select.select(
            input_socket, [], [])

        for sock in read_ready:
            if sock == server_socket:
                client_socket, client_address = server_socket.accept()
                input_socket.append(client_socket)
            else:
                data = sock.recv(4096).decode()
                print(data)

                request_header = data.split('\r\n')
                request_file = request_header[0].split()[1]

                listdir = os.listdir('.')

                if (request_file == '/' or request_file == '/index.html' or request_file == '/index.php') and ('index.html' in listdir or '/index.php' in listdir):
                    if(request_file != '/'):
                        filename = request_file[1:]
                    else:
                        filename = "index.html"
                    f = open(filename, 'r')
                    response_data = f.read()
                    f.close()

                    content_length = len(response_data)
                    response_header = 'HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=utf-8\r\nContent-Length: ' + \
                        str(content_length) + '\r\n\r\n'

                else:
                    request_file = 'list.html'
                    arr = os.listdir('.')
                    f = open('list.html', 'w')
                    # Some custom HTML code, possibly generated by another function
                    html = f"""
                            <!DOCTYPE html>
                            <html lang="en">
                            <head>
                                <meta charset="UTF-8">
                                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                                <title>Document</title>
                            </head>
                            <body>
                                <h1>List of files</h1>
                                <ul>
                            """
                    for i in arr:
                        html += f"""
                                <a href="{i}" download>{i}</a></br>
                                """
                    html += f"""
                                </ul>
                            </body>
                            </html>
                            """

                    # Writing the HTML contents with UTF-8
                    f.write(textwrap.dedent(html))
                    f.close()

                    g = open('list.html', 'r')
                    response_data = g.read()
                    g.close()

                    content_length = len(response_data)
                    response_header = 'HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=utf-8\r\nContent-Length: ' + \
                        str(content_length) + '\r\n' + str(arr) + '\r\n\r\n'

                send_data = response_header.encode() + response_data.encode()
                sock.sendall(send_data)


except KeyboardInterrupt:
    print('\nServer is shutting down...')
    server_socket.close()
    sys.exit()
